### ISSUE TITLE
kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin on Mac

### ISSUE THREAD

**Issue by yanlb** [kivy/kivy-ios#377]
When I click on the button that calls the function (v_player) to play the corporate video I get this error:

File "kivy/lib/gstplayer/_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin

I'm developing on a Mac (Mojave version: 10.14.5) using PyCharm (2019.1.1).

Project Interpreter: (Python 3.7) 
Cython 0.29.7 
Kivy 1.10.1 
Kivy-Garden 0.1.4
Pygments 2.3.1
certifi 2019.3.9
chardet 3.0.4
docopt 0.6.2
docutils 0.14
future 0.17.1 
gstreamer-player 1.1.2
idna 2.8
mutagen 1.42.0 openstep-parser
pbxproj 2.5.1
pip 19.0.3 
requests 2.21.0 
setuptools 40.8.0 
urllib3 1.24.2 
wheel 0.33.1

I have reviewed the installation, updated or reinstalled the packages: gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly

I also did this: (What did work was removing the 'gstplayer' in my kivy install. Where ever you kivy install is some where in 'site-packages/kivy/lib/gstplayer' Do rm -R site-packages/kivy/lib/gstplayer Again, this path should be replaced with your local installation path.

Based on the comments here in this issue on the kivy github site. There the directory is called 'gstreamer'. In my installation it was called 'gstplayer'.) And not work for me.

Ptyhon code:

class Presentation(Screen):
```

    def v_player(self):
        if App.get_running_app().play == 0:
            App.get_running_app().play = 1
            App.get_running_app().video = Video(source='data/video/video.mp4')
            App.get_running_app().video.state = 'play'
            App.get_running_app().video.allow_stretch = True
            self.add_widget(App.get_running_app().video)
        else:
            App.get_running_app().play = 1
```
.kv Code:

```
        FloatLayout:
            ImageButton:
                source: 'data/icons/playback_play_icon48.png'
                size_hint: .5, .5
                pos_hint: {'center_y': 0.50, 'center_x': 0.50}
                on_press: root.v_player()
```
I have read a lot on Google, I have reinstalled everything, I have tried several solutions like those described above but I have not been able to solve the problem

Any idea? Thanks in advance
